title: BanditHijo [R]-Chive
description: Here's where I started writing some notes that someday I will call it, a book.
baseurl: /
url: https://bandithijo.github.io/v2

plugins:
  - jekyll-sitemap
  - jekyll-feed

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks-option

feed:
  categories:
    - blog
    - note

sitemap:
  filename: /sitemap.xml
  exclude:
    - /feed.xml
    - /feed/blog.xml
    - /feed/note.xml
  include_posts:
    - /index.html

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
