title: BanditHijo [R]-Chive
description: Here's where I started writing some notes that someday I will call it, a book.
baseurl: ''
url: https://bandithijo.github.io/v2

author: Assyaufi, Rizqi Nur
logo_author: /assets/images/logo_author.png

image:
  path: /assets/images/bndt_banner_v2.png
  width: 460
  height: 120

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks-option
    - experimental

feed:
  excerpt_only: true

sitemap:
  filename: /sitemap.xml
  exclude:
    - /feed.xml
  include_posts:
    - /index.html

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
