title: BanditHijo [R]-Chive
description: Here's where I started writing some notes that someday I will call it, a book.
baseurl: ''
url: https://bandithijo.github.io/v2

author: Assyaufi, Rizqi Nur
logo_author: /assets/images/logo_author.png

google_analytics_id: UA-116004889-5

image:
  path: /assets/images/bndt_banner_v2.png
  width: 460
  height: 200

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=pygments
    - pygments-stylesheet!
    - icons=font
    - hardbreaks-option
    - experimental
    - table-caption=Tabel
    - figure-caption=Gambar

feed:
  excerpt_only: true

sitemap:
  filename: /sitemap.xml
  exclude:
    - /feed.xml
  include_posts:
    - /index.html

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
