= Injeksi Null Audio Source dengan FFMPEG ke dalam Video
Assyaufi, Rizqi Nur
:page-email: bandithijo@gmail.com
:page-navtitle: Injeksi Null Audio Source dengan FFMPEG ke dalam Video
:page-excerpt: Menginjeksi audio kosong (null) ke dalam video yang tidak memiliki audio source. Cara ini saya pergunakan untuk memanipulasi video yang akan saya kirim ke Telegram, agar tidak terbaca menjadi Gif.
:page-permalink: /blog/:title
:page-categories: blog
:page-tags: [ffmpeg]
:page-liquid:
:page-published: true

Menginjeksi audio kosong (null) ke dalam video yang tidak memiliki audio source. Cara ini saya pergunakan untuk memanipulasi video yang akan saya kirim ke Telegram, agar tidak terbaca menjadi Gif.

== Penyelesaian Masalah

Formula ffmpegnya bisa seperti ini.

[source,bash]
----
ffmpeg \
-i original_video.mp4 \
-f lavfi \  <1>
-i anullsrc \  <2>
-c:v copy -c:a aac \
-shortest \
target_video.mp4
----

<1> Format `-f` gunakan `lavfi`
<2> *anullsrc* adalah aktor utamanya

====
anullsrc:: The null audio source, return unprocessed audio frames. It is mainly useful as a template and to be employed in analysis / debugging tools, or as the source for filters which ignore the input data (for example the sox synth filter).

[.text-right]
-- man ffmpeg-filters
====

====
lavfi:: Libavfilter input virtual device. This input device reads data from the open output pads of a libavfilter filtergraph.

[.text-right]
-- man ffmpeg-devices
====

Tinggal diimplementasikan sesukanya.

== Referensi

. link:https://man.archlinux.org/man/ffmpeg-filters.1#anullsrc[https://man.archlinux.org/man/ffmpeg-filters.1#anullsrc^]
Diakses tanggal: 2021/07/15

. link:https://man.archlinux.org/man/ffmpeg-devices.1.en#lavfi[https://man.archlinux.org/man/ffmpeg-devices.1.en#lavfi^]
Diakses tanggal: 2021/07/15

. link:https://trac.ffmpeg.org/wiki/Null#anullsrc[https://trac.ffmpeg.org/wiki/Null#anullsrc^]
Diakses tanggal: 2021/07/19
