= Catatan Instalasi OpenBSD
Assyaufi, Rizqi Nur
:page-email: bandithijo@gmail.com
:page-navtitle: Catatan Instalasi OpenBSD
:page-excerpt: Migrasi ke OpenBSD mungkin akan menjadi perjalanan yang panjang dan penuh rintangan. Karena proses migrasi dilakukan diwaktu luang, kemungkinan untuk lupa akan sangat besar. Saya merasa perlu untuk mendokumentasikan catatan, agar tidak lupa begitu saja.
:page-permalink: /note/:title
:page-categories: note
:page-tags: [openbsdh]
:page-liquid:
:page-published: true

Migrasi ke OpenBSD mungkin akan menjadi perjalanan yang panjang dan penuh rintangan. Karena prosesnya yang tidak sekali waktu langsung selesai, namun saya cicil di waktu luang, maka saya merasa perlu untuk mendokumentasikan catatan, agar tidak hilang begitu saja.

Saya mempublikasikan catatan untuk teman-teman pembaca Blog BaditHijo, agar dapat sama-sama kita manfaatkan.
Terima kasih telah menjadi pembaca setia dan menemani saya sampai saat ini.

== Troubleshooting

=== Mengakses Root

Untuk berpindah ke root shell, dapat menggunakan.

[source,console]
----
$ su
----

Masukkan password root yang dibuat pada saat proses instalasi.

=== Root permission from user

`doas` is preinstalled by default, kita hanya perlu melakukan konfigurasi,

./etc/doas.conf
[source,conf,linenums]
----
permit :wheel
----

Kalau kita mau user hanya memasukkan password sekali, dan sementara waktu tidak perlu memasukkan password,

./etc/doas.conf
[source,conf,linenums]
----
permit persist :wheel
----

=== Text editor

`vi` is preinstalled by default, jadi kita dapat menggunakan text editor ini untuk sementara sambil menikmati suasana.

[source,console]
----
$ vi
----

=== Neovim

[source,console]
----
$ doas pkg_add neovim
----

=== Firmware update

Dapat dilakukan dengan:

[source,console]
----
$ fw_update
----

=== USB tethering

Melihat interface dari usb tethering,

[source,console]
----
$ ifconfig
----

----
...


urndis0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1500
        lladdr 0a:12:52:cf:95:21
        index 5 priority 0 llprio 3
----

Biasanya akan bernama *urndis0*.

Tinggal kita jalankan,

[source,console]
----
# dhclient urndis0  <1>
----
<1> Nama dari usb interface dapat berbeda.

Kalau berhasil, kita akan mendapatkan IP address.

----
urndis0: 192.168.42.224 lease accepted from 192.168.42.129 (6e:45:af:fc:be:9f)
----

Kalau kita cek dengan `ifconfig`.

----
urndis0: flags=808843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,AUTOCONF4> mtu 1500
        lladdr d2:58:ec:ab:0c:62
        index 5 priority 0 llprio 3
        inet 192.168.42.224 netmask 0xffffff00 broadcast 192.168.42.255
----

=== Connect Wifi

Untuk melakukan scaning, misal wifi interface kita *iwn0*.

TIP: dapat ditebak kalau wireless card saya adalah intel.

Nyalakan interface terlebih dahulu, apabila masih off.

[source,console]
----
$ ipconfig iwn0 up
----

Lakukan scanning terhadap SSID yang tersedia di sekitar.

[source,console]
----
# ipconfig iwn0 scan
----

Kemudian, setelah mendapatkan SSID yang kita inginkan, tinggal connect.

[source,console]
----
ifconfig iwn0 nwid <network-name> wpakey <passphrase>
----

Kemudian, untuk mendapatkan IP address, dapat menggunakan dhcp.

[source,console]
----
# dhclient iwn0
----

Sampai tahap ini, seharusnya sudah dapat terkoneksi ke internet.

=== DHCP Server

Jika ingin mengaktifkan DHCP server service saat startup, dapat menggunakan,

[source,console]
----
# rcctl enable dhcpd
----

Atau untuk mengeset perinterface saja, dapat menggunkan,

Misal, untuk etheret interface *em0* dan *iwn0*.

[source,console]
----
# rcctl set dhcpd flags em0 iwn0
----

=== Tmux

Sejak OpeBSD 4.6, tmux telah menjadi bagian dari base system, sehingga kita tidak perlu repot-repot memasangnya.

Tinggal jalankan tmux di terminal.

[source,console]
----
$ tmux
----

=== Starting X (Xenodm)

The recommended way to run X is with the xenodm(1) display manager. It offers some important security benefits over the traditional startx(1) command.
If xenodm(1) wasn't enabled during installation, it can be done so later like any other system daemon:

[source,console]
----
# rcctl enable xenodm
# rcctl start xenodm
----

On some platforms, you will need to disable the console getty(8) to use it. *This is not needed on amd64, i386 or macppc*.

Cara di atas akan meng-enable-kan Display Manager yang --mungkin bernama-- *xenodm*.

Dan ketika kita login, default sessionnya adalah *fvwm* yang merupakan turunan dari *twm*.

Kalau ingin menggunakan dwm,

.$HOME/.xsession
[source,conf,linenums]
----
dwm
----

=== Mirror pkg_add OpenBSD

Versi OpenBSD yang baru-baru menyimpan mirror pada */etc/installurl*.

./etc/installurl
[source,conf,linenums]
----
https://cdn.openbsd.org/pub/OpenBSD
----

=== Xorg

./etc/X11/xorg.conf.d/20-intel.conf
[source,conf,linenums]
----
Section "Device"
    Identifier    "Intel Graphics"
    Driver        "intel"

    Option        "DRI"          "true"

    Option        "DRI"          "2"
    Option        "AccellMethod" "uxa"    # Fallback

    #Option        "DRI"          "3"      # DRI 3 is now default
    #Option        "AccellMethod" "sna"    # Default

    Option        "TearFree"     "true"
EndSection
----

=== Git

[source,console]
----
$ doas pkg_add git
----

=== dwm

[source,console]
----
$ git clone https://git.suckless.org/dwm
----

.$HOME/.xsession
[source,conf,linenums]
----
xsetroot -name " OpenBSD 6.9"
xcompmgr &
dwm
----

=== st

[source,console]
----
$ git clone https://git.suckless.org/st
----

=== dmenu

[source,console]
----
$ git clone https://git.suckless.org/dmenu
----

=== sxhkd

[source,console]
----
$ doas pkg_add sxhkd
----

=== wget

[source,console]
----
$ doas pkg_add wget
----

=== harfbuzz

[source,console]
----
$ doas pkg_add harfbuzz
----

=== Neofetch

[source,console]
----
$ doas pkg_add neofetch
----

=== htop

[source,console]
----
$ doas pkg_add htop
----

=== rofi

[source,console]
----
$ doas pkg_add rofi
----

=== jq

[source,console]
----
$ doas pkg_add jq
----

=== cmake

[source,console]
----
$ doas pkg_add cmake
$ doas pkg_add extra-cmake-modules
----

=== j4-dmenu-desktop

[source,console]
----
$ git clone https://github.com/enkore/j4-dmenu-desktop.git
$ cmake .
$ make
$ sudo make install
----

== Referensi

. link:https://www.openbsdhandbook.com/openbsd_for_linux_users/[openbsdhandbook.com/openbsd_for_linux_users/^]
